from django.db import models

# Create your models here.

class AllHouse(models.Model):
    title = models.CharField(max_length=255,null=True)
    village = models.CharField(max_length=255, null=True)
    are = models.CharField(max_length=255, null=True)
    type = models.CharField(max_length=255, null=True)
    size = models.CharField(max_length=255, null=True)
    ori = models.CharField(max_length=255, null=True)
    info = models.CharField(max_length=255, null=True)
    rent = models.CharField(max_length=255, null=True)
    people = models.CharField(max_length=255, null=True)
    dist = models.CharField(max_length=255, null=True)

class AllStockBasic(models.Model):
    code = models.CharField(max_length=255,null=True)
    name = models.CharField(max_length=255,null=True)
    industry = models.CharField(max_length=255,null=True)
    area = models.CharField(max_length=255,null=True)
    pe = models.CharField(max_length=255,null=True)
    outstanding = models.CharField(max_length=255,null=True)
    totals = models.CharField(max_length=255,null=True)
    totalAssets = models.CharField(max_length=255,null=True)
    liquidAssets = models.CharField(max_length=255,null=True)
    fixedAssets = models.CharField(max_length=255,null=True)
    reserved = models.CharField(max_length=255,null=True)
    reservedPerShare = models.CharField(max_length=255,null=True)
    esp = models.CharField(max_length=255,null=True)
    bvps = models.CharField(max_length=255,null=True)
    pb = models.CharField(max_length=255,null=True)
    timeToMarket = models.CharField(max_length=255,null=True)
    undp = models.CharField(max_length=255,null=True)
    perundp = models.CharField(max_length=255,null=True)
    rev = models.CharField(max_length=255,null=True)
    profit = models.CharField(max_length=255,null=True)
    gpr = models.CharField(max_length=255,null=True)
    npr = models.CharField(max_length=255,null=True)
    holders = models.CharField(max_length=255,null=True)

class RealTimePens(models.Model):
    code = models.CharField(max_length=255, null=True,unique=True)
    name = models.CharField(max_length=255, null=True)
    open = models.CharField(max_length=255, null=True)
    pre_close = models.CharField(max_length=255, null=True)
    price = models.CharField(max_length=255, null=True)
    high = models.CharField(max_length=255, null=True)
    low = models.CharField(max_length=255, null=True)
    bid = models.CharField(max_length=255, null=True)
    ask = models.CharField(max_length=255, null=True)
    volume = models.CharField(max_length=255, null=True)
    amount = models.CharField(max_length=255, null=True)
    date = models.CharField(max_length=255, null=True)
    time = models.CharField(max_length=255, null=True)

class HISData(models.Model):
    code = models.CharField(max_length=255,null=True)
    open = models.CharField(max_length=255,null=True)
    high = models.CharField(max_length=255,null=True)
    close = models.CharField(max_length=255,null=True)
    low = models.CharField(max_length=255,null=True)
    volume = models.CharField(max_length=255,null=True)
    price_change = models.CharField(max_length=255,null=True)
    p_change = models.CharField(max_length=255,null=True)
    ma5 = models.CharField(max_length=255,null=True)
    ma10 = models.CharField(max_length=255,null=True)
    ma20 = models.CharField(max_length=255,null=True)
    v_ma5 = models.CharField(max_length=255,null=True)
    v_ma10 = models.CharField(max_length=255,null=True)
    v_ma20 = models.CharField(max_length=255,null=True)
